"""empty message

Revision ID: 122783035b85
Revises: 45e76ad61bee
Create Date: 2022-12-20 00:28:01.861829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122783035b85'
down_revision = '45e76ad61bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('planet_from', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('planet_from')
    )
    op.create_table('peopleFavorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'people_id')
    )
    op.drop_table('characterFavorites')
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('characters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('planet_from', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='characters_pkey'),
    sa.UniqueConstraint('name', name='characters_name_key'),
    sa.UniqueConstraint('planet_from', name='characters_planet_from_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('characterFavorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='characterFavorites_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='characterFavorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'character_id', name='characterFavorites_pkey')
    )
    op.drop_table('peopleFavorites')
    op.drop_table('people')
    # ### end Alembic commands ###
